/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Dino.gltf 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Dino({ hovered, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/Dino.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    const anim = hovered ? "Wave" : "Idle";
    actions[anim].reset().fadeIn(0.5).play();

    return () => actions[anim].fadeOut(0.5);
  }, [hovered]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="CharacterArmature">
          <primitive object={nodes.Root} />
          <group name="Dino">
            <skinnedMesh
              name="Cube081"
              geometry={nodes.Cube081.geometry}
              material={materials.Dino_Main}
              skeleton={nodes.Cube081.skeleton}
            />
            <skinnedMesh
              name="Cube081_1"
              geometry={nodes.Cube081_1.geometry}
              material={materials.Dino_Secondary}
              skeleton={nodes.Cube081_1.skeleton}
            />
            <skinnedMesh
              name="Cube081_2"
              geometry={nodes.Cube081_2.geometry}
              material={materials.Eye_Black}
              skeleton={nodes.Cube081_2.skeleton}
            />
            <skinnedMesh
              name="Cube081_3"
              geometry={nodes.Cube081_3.geometry}
              material={materials.Eye_White}
              skeleton={nodes.Cube081_3.skeleton}
            />
            <skinnedMesh
              name="Cube081_4"
              geometry={nodes.Cube081_4.geometry}
              material={materials.Dino_Teeth}
              skeleton={nodes.Cube081_4.skeleton}
            />
            <skinnedMesh
              name="Cube081_5"
              geometry={nodes.Cube081_5.geometry}
              material={materials.Dino_Tongue}
              skeleton={nodes.Cube081_5.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/Dino.gltf");
